name: Deploy Flutter Web to Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.38.6
          cache: true

      - name: Flutter Version
        run: flutter --version

      - name: Enable Web
        run: flutter config --enable-web

      - name: Install Dependencies
        run: flutter pub get

      - name: Analyze Project
        run: flutter analyze

      - name: Build Web
        run: flutter build web --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-web
          path: build/web